version: '3.8'
services:
  postgres:
    image: postgres:13.3-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=appDB
      - POSTGRES_USER=adminer
      - POSTGRES_PASSWORD=password
